import { TeamMember, Technology, Offering } from "./type";

export const MISSION_FEATURES: string[] = [
  "Structured, secure vulnerability reporting",
  "Transparent evaluation & merit-based rewards",
  "Anti-cheating and plagiarism prevention",
  "Innovation through real-world challenges",
];

export const VISION_FEATURES: string[] = [
  "Globally trusted platform for all stakeholders",
  "Active, security-first collaborative community",
  "Scalable infrastructure for enterprise bounties",
  "Cybersecurity education through practice",
];

export const SUPERVISORS: TeamMember[] = [
  {
    name: "Sreng Chipor",
    badge: "Mentor",
    badgeColor: "pink",
    subRole: "Supervisor",
    quote: '"Guiding the next generation of cybersecurity experts."',
    image: "/teacherChipor.JPG",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    email: "chipor@devsolve.io",
  },
  {
    name: "Rin Bunvarn",
    badge: "Mentor",
    badgeColor: "pink",
    subRole: "Supervisor",
    quote: '"Building resilient systems through rigorous academic foundation."',
    image: "/TeacherBunVarn.jpeg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    email: "bunvarn@devsolve.io",
  },
];

export const STUDENT_DEVELOPERS: TeamMember[] = [
  {
    name: "Taing Sengkim",
    badge: "Leader",
    badgeColor: "purple",
    subRole: "Full Stack",
    quote: '"Visionary leadership drives technical success."',
    image: "/teams/Taing Sengkim.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Lor VengRoth",
    badge: "Sub Leader",
    badgeColor: "purple",
    subRole: "Full Stack",
    quote: '"Architecting the backbone of security."',
    image: "/teams/Lor VengRoth.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Bun Raksa",
    badge: "CTO",
    badgeColor: "blue",
    subRole: "Full Stack",
    quote: '"Securing the future, one line of code at a time."',
    image: "/teams/Bun Raksa.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Chamreun Molikatevy",
    badge: "Design",
    badgeColor: "blue",
    subRole: "UI/UX & Dev",
    quote: '"Crafting pixel-perfect secure experiences."',
    image: "/teams/Chamreun Molikatevy.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Dim Pathea",
    badge: "Design",
    badgeColor: "blue",
    subRole: "Frontend",
    quote: '"Design with security in mind from day one."',
    image: "/teams/Dim Pathea.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Tollah Hamadabidin",
    badge: "Backend",
    badgeColor: "blue",
    subRole: "Backend Dev",
    quote: '"Robust code is the best defense."',
    image: "/teams/Tollah Hamadabidin.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "San Tol",
    badge: "Frontend",
    badgeColor: "blue",
    subRole: "Frontend Dev",
    quote: '"Visualizing threats for better protection."',
    image: "/teams/San Tol.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Seu Narong",
    badge: "Full Stack",
    badgeColor: "blue",
    subRole: "Full Stack Dev",
    quote: '"Innovation through collaborative logic."',
    image: "/teams/Seu Narong.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
  {
    name: "Ky Reaksa",
    badge: "Full Stack",
    badgeColor: "blue",
    subRole: "Full Stack Dev",
    quote: '"Innovation through collaborative logic."',
    image: "/teams/Ky Reaksa.jpg",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    telegram: "https://t.me",
  },
];

export const TECHNOLOGIES: Technology[] = [
  {
    image: "/react1.png",
    name: "React",
    description: "Frontend UI",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-100 hover:border-sky-300",
  },
  {
    image: "/spring1.png",
    name: "Spring Boot",
    description: "Backend API",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-100 hover:border-emerald-300",
  },
  {
    image: "/postgrest1.png",
    name: "PostgreSQL",
    description: "Database",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-100 hover:border-blue-300",
  },
  {
    image: "/doker1.png",
    name: "Docker",
    description: "Containers",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-100 hover:border-cyan-300",
  },
  {
    image: "/keycloak1.png",
    name: "Keycloak",
    description: "Auth & SSO",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-100 hover:border-purple-300",
  },
  {
    image: "/tailwind1.png",
    name: "Tailwind CSS",
    description: "Styling",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-100 hover:border-teal-300",
  },
];

export const OFFERINGS: Offering[] = [
  {
    iconName: "Code",
    title: "Technical Challenges",
    description: "Real-world coding and engineering challenges with secure evaluation and confidential judging.",
    accentBg: "bg-blue-50",
    accentText: "text-blue-600",
    borderColor: "border-blue-100 hover:border-blue-200",
  },
  {
    iconName: "Bug",
    title: "Bounty Programs",
    description: "Scoped organization programs for identifying, documenting, and resolving technical vulnerabilities.",
    accentBg: "bg-red-50",
    accentText: "text-red-500",
    borderColor: "border-red-100 hover:border-red-200",
  },
  {
    iconName: "MessageSquare",
    title: "Discussion",
    description: "An integrated community forum to exchange technical insights, ask questions, and share knowledge.",
    accentBg: "bg-purple-50",
    accentText: "text-purple-600",
    borderColor: "border-purple-100 hover:border-purple-200",
  },
  // 2 more.
];