import { BookmarkItem } from "./types";

export const MOCK_BOOKMARKS: BookmarkItem[] = [
  {
    id: "bm-1",
    category: "Problems",
    title: "JWT Authentication Bypass in OAuth Flow",
    description: "Flaw in signature validation step allows signature stripping algorithm algorithm attack using 'none' algorithm token.",
    savedAt: "2 hours ago",
    tags: ["OAuth", "JWT", "Authentication", "API Security"],
    severity: "Critical",
    points: 850,
    submissionsCount: 14,
    status: "Open",
    url: "/dashboard/problems/bm-1",
  },
  {
    id: "bm-2",
    category: "Problems",
    title: "SQL Injection in User Search Endpoint",
    description: "Time-based blind SQL injection vulnerability identified within unescaped query params of administrative search interface.",
    savedAt: "5 hours ago",
    tags: ["SQLi", "Backend", "Database"],
    severity: "High",
    points: 600,
    submissionsCount: 28,
    status: "Open",
    url: "/dashboard/problems/bm-2",
  },
  {
    id: "bm-3",
    category: "Problems",
    title: "SSRF Vulnerability in Webhook Notification Handler",
    description: "Unsanitized URL endpoint parameter in custom notification integration allows fetching internal AWS metadata service.",
    savedAt: "1 day ago",
    tags: ["SSRF", "Cloud", "Webhooks"],
    severity: "High",
    points: 500,
    submissionsCount: 9,
    status: "In Review",
    url: "/dashboard/problems/bm-3",
  },
  {
    id: "bm-4",
    category: "Program",
    title: "Stripe Bug Bounty & Vulnerability Disclosure",
    description: "Security response program targeting payment API endpoints, webhooks, and partner integrations.",
    savedAt: "2 days ago",
    tags: ["Fintech", "API", "Bounty"],
    companyName: "Stripe",
    logoUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80",
    bountyMax: "$25,000",
    programType: "Bounty",
    inScopeCount: 34,
    url: "/dashboard/programs/prog-stripe",
  },
  {
    id: "bm-5",
    category: "Program",
    title: "GitHub Security Response Program",
    description: "Help protect 100M+ developers across GitHub Actions, Copilot API, and Enterprise Cloud.",
    savedAt: "3 days ago",
    tags: ["DevTools", "Cloud", "Actions"],
    companyName: "GitHub",
    logoUrl: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=128&auto=format&fit=crop&q=80",
    bountyMax: "$30,000",
    programType: "Bounty",
    inScopeCount: 52,
    url: "/dashboard/programs/prog-github",
  },
  {
    id: "bm-6",
    category: "Program",
    title: "Vercel Developer Platform Security",
    description: "Targeting Next.js runtime edge services, edge functions, and global distribution network infrastructure.",
    savedAt: "4 days ago",
    tags: ["Frontend", "Serverless", "Edge"],
    companyName: "Vercel",
    logoUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=128&auto=format&fit=crop&q=80",
    bountyMax: "$15,000",
    programType: "Bounty",
    inScopeCount: 18,
    url: "/dashboard/programs/prog-vercel",
  },
  {
    id: "bm-7",
    category: "Solutions",
    title: "Bypassing Modern WAF Rules via Unicode Normalization",
    description: "Comprehensive writeup on how character set conversions in reverse proxies bypass payload inspection layers.",
    savedAt: "5 days ago",
    tags: ["WAF", "Writeup", "Payloads"],
    authorName: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80",
    readTime: "8 min read",
    likesCount: 342,
    targetProgram: "Web Application Firewall Research",
    url: "/dashboard/solutions/sol-1",
  },
  {
    id: "bm-8",
    category: "Solutions",
    title: "Zero-Day Breakdown: RCE via Unsafe Deserialization in API Gateway",
    description: "Deep dive into object graph construction flaws leading to remote code execution in microservice proxies.",
    savedAt: "1 week ago",
    tags: ["RCE", "Deserialization", "Deep Dive"],
    authorName: "Elena Rostova",
    authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=128&auto=format&fit=crop&q=80",
    readTime: "12 min read",
    likesCount: 512,
    targetProgram: "API Gateway Exploitation",
    url: "/dashboard/solutions/sol-2",
  },
];
