import { ProgramItem } from "./types";

export const MOCK_PROGRAMS: ProgramItem[] = [
  {
    id: "prog-1",
    companyName: "NexaCloude",
    companySlug: "nexacloude",
    logoUrl: "/NexaCloude.png",
    logoBgColor: "bg-blue-600",
    type: "Response",
    status: "Archived",
    isNew: false,
    isPrivate: true,
    title: "Uber Security Disclosure Program",
    description:
      "Archived disclosure program covering Uber's rider and driver apps and marketplace infrastructure.",
    inScopeAssets: ["*.uber.com", "rider.uber.com", "driver.uber.com", "iOS App"],
    assetCategories: ["Web", "Mobile", "API"],
    rewardRange: "+10 - +50 pts",
    rewardType: "points",
    stats: {
      reportsSubmitted: 142,
      responseTime: "2 days",
    },
  },
  {
    id: "prog-2",
    companyName: "Microsoft",
    companySlug: "microsoft",
    logoUrl: "/microsoft.png",
    logoBgColor: "bg-emerald-600",
    type: "Bounty",
    status: "Done",
    isNew: false,
    isPrivate: false,
    title: "Microsoft MSRC Bug Bounty",
    description:
      "Completed round of Microsoft's Security Response Center bounty covering Azure and M365.",
    inScopeAssets: ["*.microsoft.com", "*.azure.com", "*.office.com", "Windows"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$500 - $100,000",
    rewardType: "bounty",
    totalBountyPaid: "$2.4M+",
    stats: {
      reportsSubmitted: 890,
      avgPayout: "$4,500",
      responseTime: "1 day",
    },
  },
  {
    id: "prog-3",
    companyName: "Netflix",
    companySlug: "netflix",
    logoUrl: "/netflix.png",
    logoBgColor: "bg-rose-600",
    type: "Response",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Netflix Coordinated Disclosure",
    description:
      "Responsible disclosure for Netflix's streaming platform, APIs, and partner integrations.",
    inScopeAssets: ["*.netflix.com", "api.netflix.com", "iOS App", "Android App"],
    assetCategories: ["Web", "API", "Mobile"],
    rewardRange: "+20 - +80 pts",
    rewardType: "points",
    stats: {
      reportsSubmitted: 310,
      responseTime: "3 days",
    },
  },
  {
    id: "prog-4",
    companyName: "NexaCloude",
    companySlug: "nexacloude-2",
    logoUrl: "/NexaCloude.png",
    logoBgColor: "bg-indigo-600",
    type: "Response",
    status: "Archived",
    isNew: false,
    isPrivate: true,
    title: "Uber Security Disclosure Program",
    description:
      "Archived disclosure program covering Uber's rider and driver apps and marketplace infrastructure.",
    inScopeAssets: ["*.uber.com", "rider.uber.com", "driver.uber.com", "iOS App"],
    assetCategories: ["Web", "Mobile"],
    rewardRange: "+10 - +50 pts",
    rewardType: "points",
  },
  {
    id: "prog-5",
    companyName: "Microsoft",
    companySlug: "microsoft-2",
    logoUrl: "/microsoft.png",
    logoBgColor: "bg-cyan-600",
    type: "Bounty",
    status: "Done",
    isNew: false,
    isPrivate: false,
    title: "Microsoft MSRC Bug Bounty",
    description:
      "Completed round of Microsoft's Security Response Center bounty covering Azure and M365.",
    inScopeAssets: ["*.microsoft.com", "*.azure.com", "*.office.com", "Windows"],
    assetCategories: ["Web", "API"],
    rewardRange: "$500 - $100,000",
    rewardType: "bounty",
  },
  {
    id: "prog-6",
    companyName: "Netflix",
    companySlug: "netflix-2",
    logoUrl: "/netflix.png",
    logoBgColor: "bg-red-700",
    type: "Response",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Netflix Coordinated Disclosure",
    description:
      "Responsible disclosure for Netflix's streaming platform, APIs, and partner integrations.",
    inScopeAssets: ["*.netflix.com", "api.netflix.com", "iOS App", "Android App"],
    assetCategories: ["Web", "Mobile", "API"],
    rewardRange: "+20 - +80 pts",
    rewardType: "points",
  },
  {
    id: "prog-7",
    companyName: "GitHub",
    companySlug: "github",
    logoUrl: "/Github.png",
    logoBgColor: "bg-slate-900",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "GitHub Security Bug Bounty",
    description:
      "Help secure GitHub Enterprise, GitHub Copilot, and core REST & GraphQL APIs.",
    inScopeAssets: ["github.com", "api.github.com", "*.githubenterprise.com", "Actions"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$610 - $30,000",
    rewardType: "bounty",
  },
  {
    id: "prog-8",
    companyName: "Cloudflare",
    companySlug: "cloudflare",
    logoUrl: "/Cloudflare.png",
    logoBgColor: "bg-orange-500",
    type: "Bounty",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Cloudflare Edge Security Program",
    description:
      "Vulnerability rewards for Cloudflare Workers, DNS edge nodes, and Zero Trust gateways.",
    inScopeAssets: ["*.cloudflare.com", "workers.dev", "1.1.1.1 DNS", "WARP Client"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$250 - $25,000",
    rewardType: "bounty",
  },
  {
    id: "prog-9",
    companyName: "Google",
    companySlug: "google",
    logoUrl: "/Google.png",
    logoBgColor: "bg-emerald-500",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Google Vulnerability Reward Program (VRP)",
    description:
      "Security rewards for Google Cloud Platform, Workspace, Android OS, and Chrome browser.",
    inScopeAssets: ["*.google.com", "cloud.google.com", "Android OS", "Chrome Core"],
    assetCategories: ["Web", "API", "Mobile", "Network"],
    rewardRange: "$500 - $133,337",
    rewardType: "bounty",
  },
  {
    id: "prog-10",
    companyName: "Tesla",
    companySlug: "tesla",
    logoUrl: "/Tesla.png",
    logoBgColor: "bg-rose-700",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Tesla Product Security Bounty",
    description:
      "Bounty program covering vehicle telemetry, mobile apps, and Tesla Energy endpoints.",
    inScopeAssets: ["tesla.com", "mobile-api.tesla.com", "Tesla iOS", "Tesla Android"],
    assetCategories: ["Web", "API", "Mobile"],
    rewardRange: "$100 - $15,000",
    rewardType: "bounty",
  },
  {
    id: "prog-11",
    companyName: "Spotify",
    companySlug: "spotify",
    logoBgColor: "bg-green-600",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Spotify Player & API Bounty",
    description:
      "Find vulnerabilities in Spotify web player, mobile SDKs, and developer portal APIs.",
    inScopeAssets: ["spotify.com", "api.spotify.com", "Spotify iOS", "Spotify Desktop"],
    assetCategories: ["Web", "API", "Mobile"],
    rewardRange: "$250 - $10,000",
    rewardType: "bounty",
  },
  {
    id: "prog-12",
    companyName: "NexaCloude",
    companySlug: "nexacloude-3",
    logoUrl: "/NexaCloude.png",
    logoBgColor: "bg-blue-600",
    type: "Response",
    status: "Archived",
    isNew: false,
    isPrivate: true,
    title: "Uber Security Disclosure Program",
    description:
      "Archived disclosure program covering Uber's rider and driver apps and marketplace infrastructure.",
    inScopeAssets: ["*.uber.com", "rider.uber.com", "driver.uber.com", "iOS App"],
    assetCategories: ["Web", "Mobile"],
    rewardRange: "+10 - +50 pts",
    rewardType: "points",
  },
];
