import { ProgramItem } from "./types";

export const DEFAULT_POC_REQUIREMENTS = [
  "Step-by-step reproduction guide",
  "Exact HTTP request/payload (use Burp Suite export)",
  "Screenshot or screen recording demonstrating impact",
  "Affected endpoint and parameter names",
];

export const DEFAULT_RULES_EXCLUSIONS = [
  "Denial of Service (DoS/DDoS) attacks against production nodes",
  "Spam, phishing, or social engineering targeting employees or users",
  "Physical security testing of data centers or office locations",
  "Automated vulnerability scanner noise without validated proof of concept",
  "Third-party integrations or services not directly controlled by the target",
];

export const DEFAULT_BOUNTY_MATRIX = [
  { severity: "CRITICAL", range: "$5,000 - $10,000", description: "Remote Code Execution (RCE), Authentication Bypass, Full Database Leak" },
  { severity: "HIGH", range: "$2,000 - $5,000", description: "Stored XSS, Account Takeover, Privilege Escalation, Broken Access Control" },
  { severity: "MEDIUM", range: "$500 - $2,000", description: "CSRF on critical actions, IDOR, Server-Side Request Forgery (SSRF)" },
  { severity: "LOW", range: "$100 - $500", description: "Reflected XSS, Open Redirect, Sensitive Information Disclosure" },
];

export const MOCK_PROGRAMS: ProgramItem[] = [
  {
    id: "prog-1",
    companyName: "NexaCloud",
    companySlug: "nexacloud",
    logoUrl: "/NexaCloude.png",
    logoBgColor: "bg-blue-600",
    type: "Bounty",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Core Infrastructure Security",
    description:
      "NexaCloud is a leading cloud infrastructure provider serving 12,000+ businesses globally with compute, storage, and networking solutions.",
    inScopeAssets: ["*.nexacloud.com", "api.nexacloud.com", "console.nexacloud.com", "iOS App", "Android App"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$1,000 - $10,000",
    rewardType: "bounty",
    maxReward: "$10,000",
    researchersCount: 89,
    startDate: "June 1, 2025",
    endDate: "Aug 31, 2025",
    aboutSummary:
      "Test our cloud infrastructure, API gateways, and core web services for vulnerabilities. NexaCloud is a leading cloud infrastructure provider serving 12,000+ businesses globally with compute, storage, and networking solutions.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    stats: {
      reportsSubmitted: 142,
      avgPayout: "$3,200",
      responseTime: "2 days",
    },
  },
  {
    id: "prog-2",
    companyName: "Microsoft",
    companySlug: "microsoft",
    logoUrl: "/microsoft.png",
    logoBgColor: "bg-emerald-600",
    type: "Bounty",
    status: "Done",
    isNew: false,
    isPrivate: false,
    title: "Microsoft MSRC Bug Bounty",
    description:
      "Completed round of Microsoft's Security Response Center bounty covering Azure and M365.",
    inScopeAssets: ["*.microsoft.com", "*.azure.com", "*.office.com", "Windows"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$500 - $100,000",
    rewardType: "bounty",
    maxReward: "$100,000",
    researchersCount: 420,
    startDate: "Jan 1, 2025",
    endDate: "Dec 31, 2025",
    aboutSummary: "Security research for Azure cloud services, M365 enterprise endpoints, and core Windows API security.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    totalBountyPaid: "$2.4M+",
    stats: {
      reportsSubmitted: 890,
      avgPayout: "$4,500",
      responseTime: "1 day",
    },
  },
  {
    id: "prog-3",
    companyName: "Netflix",
    companySlug: "netflix",
    logoUrl: "/netflix.png",
    logoBgColor: "bg-rose-600",
    type: "Response",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Netflix Coordinated Disclosure",
    description:
      "Responsible disclosure for Netflix's streaming platform, APIs, and partner integrations.",
    inScopeAssets: ["*.netflix.com", "api.netflix.com", "iOS App", "Android App"],
    assetCategories: ["Web", "API", "Mobile"],
    rewardRange: "+20 - +80 pts",
    rewardType: "points",
    maxReward: "+80 pts",
    researchersCount: 156,
    startDate: "Mar 15, 2025",
    endDate: "Continuous",
    aboutSummary: "Find vulnerabilities across Netflix streaming playback servers, subscriber account portals, and partner APIs.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    stats: {
      reportsSubmitted: 310,
      responseTime: "3 days",
    },
  },
  {
    id: "prog-4",
    companyName: "Cloudflare",
    companySlug: "cloudflare",
    logoUrl: "/Cloudflare.png",
    logoBgColor: "bg-orange-500",
    type: "Bounty",
    status: "Open",
    isNew: true,
    isPrivate: false,
    title: "Cloudflare Edge Security Program",
    description:
      "Vulnerability rewards for Cloudflare Workers, DNS edge nodes, and Zero Trust gateways.",
    inScopeAssets: ["*.cloudflare.com", "workers.dev", "1.1.1.1 DNS", "WARP Client"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$250 - $25,000",
    rewardType: "bounty",
    maxReward: "$25,000",
    researchersCount: 210,
    startDate: "Feb 1, 2025",
    endDate: "Nov 30, 2025",
    aboutSummary: "Vulnerability rewards for Cloudflare Workers, DNS edge nodes, and Zero Trust gateways.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    stats: {
      reportsSubmitted: 245,
      responseTime: "1 day",
    },
  },
  {
    id: "prog-5",
    companyName: "Google",
    companySlug: "google",
    logoUrl: "/Google.png",
    logoBgColor: "bg-emerald-500",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Google Vulnerability Reward Program (VRP)",
    description:
      "Security rewards for Google Cloud Platform, Workspace, Android OS, and Chrome browser.",
    inScopeAssets: ["*.google.com", "cloud.google.com", "Android OS", "Chrome Core"],
    assetCategories: ["Web", "API", "Mobile", "Network"],
    rewardRange: "$500 - $133,337",
    rewardType: "bounty",
    maxReward: "$133,337",
    researchersCount: 980,
    startDate: "Jan 1, 2025",
    endDate: "Continuous",
    aboutSummary: "Security rewards for Google Cloud Platform, Workspace, Android OS, and Chrome browser.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    stats: {
      reportsSubmitted: 1450,
      responseTime: "1 day",
    },
  },
  {
    id: "prog-6",
    companyName: "GitHub",
    companySlug: "github",
    logoUrl: "/Github.png",
    logoBgColor: "bg-slate-900",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "GitHub Security Bug Bounty",
    description:
      "Help secure GitHub Enterprise, GitHub Copilot, and core REST & GraphQL APIs.",
    inScopeAssets: ["github.com", "api.github.com", "*.githubenterprise.com", "Actions"],
    assetCategories: ["Web", "API", "Network"],
    rewardRange: "$610 - $30,000",
    rewardType: "bounty",
    maxReward: "$30,000",
    researchersCount: 340,
    startDate: "Jan 1, 2025",
    endDate: "Continuous",
    aboutSummary: "Help secure GitHub Enterprise, GitHub Copilot, and core REST & GraphQL APIs.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    stats: {
      reportsSubmitted: 620,
      responseTime: "2 days",
    },
  },
  {
    id: "prog-7",
    companyName: "Tesla",
    companySlug: "tesla",
    logoUrl: "/Tesla.png",
    logoBgColor: "bg-rose-700",
    type: "Bounty",
    status: "Open",
    isNew: false,
    isPrivate: false,
    title: "Tesla Product Security Bounty",
    description:
      "Bounty program covering vehicle telemetry, mobile apps, and Tesla Energy endpoints.",
    inScopeAssets: ["tesla.com", "mobile-api.tesla.com", "Tesla iOS", "Tesla Android"],
    assetCategories: ["Web", "API", "Mobile"],
    rewardRange: "$100 - $15,000",
    rewardType: "bounty",
    maxReward: "$15,000",
    researchersCount: 175,
    startDate: "Jan 1, 2025",
    endDate: "Continuous",
    aboutSummary: "Bounty program covering vehicle telemetry, mobile apps, and Tesla Energy endpoints.",
    pocRequirements: DEFAULT_POC_REQUIREMENTS,
    rulesExclusions: DEFAULT_RULES_EXCLUSIONS,
    bountyMatrix: DEFAULT_BOUNTY_MATRIX,
    stats: {
      reportsSubmitted: 280,
      responseTime: "3 days",
    },
  },
];
