import { HacktivityActivity, HacktivityStat, HacktivityFeedResponse } from "./types";

export const HACKTIVITY_STATS: HacktivityStat[] = [
  { label: "Hackers", value: "42,813" },
  { label: "Reports Resolved", value: "184,290" },
  { label: "Total Paid Out", value: "$28.4M" },
  { label: "Programs Active", value: "1,940" },
];

export const HACKTIVITY_ACTIVITIES: HacktivityActivity[] = [
  {
    id: "a1",
    initials: "0X",
    handle: "0xd3v11",
    avatarUrl: "https://i.pinimg.com/736x/28/58/cf/2858cf0eedebed2c21e7d286d62e6ee9.jpg",
    label: "NEW",
    action: "found and resolved a Critical Remote Code Execution vulnerability",
    program: "Stripe",
    severity: "Critical",
    bounty: "Bounty",
    paid: "$20,000",
    rep: "9,240 rep",
    timeAgo: "2m ago",
  },
  {
    id: "a2",
    initials: "SN",
    handle: "sec_ninja",
    avatarUrl: "https://i.pinimg.com/736x/28/58/cf/2858cf0eedebed2c21e7d286d62e6ee9.jpg",
    label: "NEW",
    action: "found and resolved a High SQL Injection vulnerability",
    program: "Shopify",
    severity: "High",
    bounty: "Bounty",
    paid: "$8,500",
    rep: "7,810 rep",
    timeAgo: "14m ago",
  },
  {
    id: "a3",
    initials: "WZ",
    handle: "whitehat_z",
    avatarUrl: "https://i.pinimg.com/736x/28/58/cf/2858cf0eedebed2c21e7d286d62e6ee9.jpg",
    label: "UPDATE",
    action: "escalated a Medium CSRF issue to triage",
    program: "Discord",
    severity: "Medium",
    bounty: "Bounty",
    paid: "$1,200",
    rep: "3,140 rep",
    timeAgo: "18m ago",
  },
  {
    id: "a4",
    initials: "AK",
    handle: "audit_kate",
    avatarUrl: "https://i.pinimg.com/736x/28/58/cf/2858cf0eedebed2c21e7d286d62e6ee9.jpg",
    label: "NEW",
    action: "reported a Low information disclosure bug",
    program: "Zoom",
    severity: "Low",
    bounty: "Bounty",
    paid: "$480",
    rep: "1,020 rep",
    timeAgo: "26m ago",
  },
  {
    id: "a5",
    initials: "PH",
    handle: "ph0enix",
    avatarUrl: "https://i.pinimg.com/736x/28/58/cf/2858cf0eedebed2c21e7d286d62e6ee9.jpg",
    label: "UPDATE",
    action: "resolved a High auth bypass issue",
    program: "Okta",
    severity: "High",
    bounty: "Bounty",
    paid: "$7,100",
    rep: "6,720 rep",
    timeAgo: "34m ago",
  },
];

export const HACKTIVITY_FEED_RESPONSE: HacktivityFeedResponse = {
  stats: HACKTIVITY_STATS,
  activities: HACKTIVITY_ACTIVITIES,
};
