import type { DiagramTemplate } from "./types";

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  {
    id: "erd-ecommerce",
    name: "E-Commerce Schema (ERD)",
    description: "Relational database schema: Users, Products, Categories, Orders, and Order Items",
    nodes: [
      {
        id: "tbl-users",
        type: "tableNode",
        position: { x: 50, y: 50 },
        data: {
          label: "users",
          tableName: "users",
          subtext: "User accounts & auth data",
          badge: "TABLE",
          colorTheme: "blue",
          columns: [
            { id: "u-id", name: "id", type: "UUID", isPk: true },
            { id: "u-email", name: "email", type: "VARCHAR(255)", isUnique: true },
            { id: "u-name", name: "full_name", type: "VARCHAR(120)" },
            { id: "u-role", name: "role", type: "VARCHAR(30)" },
            { id: "u-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-categories",
        type: "tableNode",
        position: { x: 420, y: 50 },
        data: {
          label: "categories",
          tableName: "categories",
          subtext: "Product categories hierarchy",
          badge: "TABLE",
          colorTheme: "amber",
          columns: [
            { id: "c-id", name: "id", type: "UUID", isPk: true },
            { id: "c-name", name: "name", type: "VARCHAR(100)" },
            { id: "c-slug", name: "slug", type: "VARCHAR(120)", isUnique: true },
            { id: "c-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-products",
        type: "tableNode",
        position: { x: 420, y: 320 },
        data: {
          label: "products",
          tableName: "products",
          subtext: "Inventory catalog items",
          badge: "TABLE",
          colorTheme: "emerald",
          columns: [
            { id: "p-id", name: "id", type: "UUID", isPk: true },
            { id: "p-cat-id", name: "category_id", type: "UUID", isFk: true },
            { id: "p-name", name: "title", type: "VARCHAR(200)" },
            { id: "p-price", name: "price", type: "NUMERIC(10,2)" },
            { id: "p-stock", name: "stock_quantity", type: "INTEGER" },
            { id: "p-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-orders",
        type: "tableNode",
        position: { x: 50, y: 350 },
        data: {
          label: "orders",
          tableName: "orders",
          subtext: "Customer order header",
          badge: "TABLE",
          colorTheme: "indigo",
          columns: [
            { id: "o-id", name: "id", type: "UUID", isPk: true },
            { id: "o-user-id", name: "user_id", type: "UUID", isFk: true },
            { id: "o-total", name: "total_amount", type: "NUMERIC(12,2)" },
            { id: "o-status", name: "status", type: "VARCHAR(50)" },
            { id: "o-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-order-items",
        type: "tableNode",
        position: { x: 420, y: 640 },
        data: {
          label: "order_items",
          tableName: "order_items",
          subtext: "Line items in an order",
          badge: "TABLE",
          colorTheme: "purple",
          columns: [
            { id: "oi-id", name: "id", type: "UUID", isPk: true },
            { id: "oi-order-id", name: "order_id", type: "UUID", isFk: true },
            { id: "oi-prod-id", name: "product_id", type: "UUID", isFk: true },
            { id: "oi-qty", name: "quantity", type: "INTEGER" },
            { id: "oi-unit-price", name: "unit_price", type: "NUMERIC(10,2)" },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e-users-orders",
        source: "tbl-users",
        sourceHandle: "col-right-u-id",
        target: "tbl-orders",
        targetHandle: "col-left-o-user-id",
        label: "1 : N (user orders)",
        animated: false,
      },
      {
        id: "e-cat-prod",
        source: "tbl-categories",
        sourceHandle: "col-right-c-id",
        target: "tbl-products",
        targetHandle: "col-right-p-cat-id",
        label: "1 : N (category products)",
        animated: false,
      },
      {
        id: "e-order-items-order",
        source: "tbl-orders",
        sourceHandle: "col-right-o-id",
        target: "tbl-order-items",
        targetHandle: "col-left-oi-order-id",
        label: "1 : N (has items)",
        animated: false,
      },
      {
        id: "e-prod-items",
        source: "tbl-products",
        sourceHandle: "col-right-p-id",
        target: "tbl-order-items",
        targetHandle: "col-right-oi-prod-id",
        label: "1 : N (product in items)",
        animated: false,
      },
    ],
  },
  {
    id: "erd-devsolve",
    name: "DevSolve Platform Schema (ERD)",
    description: "Entities for problems, solutions, comments, tags, and profiles",
    nodes: [
      {
        id: "tbl-dev-users",
        type: "tableNode",
        position: { x: 50, y: 60 },
        data: {
          label: "users",
          tableName: "users",
          subtext: "Authentication credentials & identity",
          badge: "TABLE",
          colorTheme: "blue",
          columns: [
            { id: "du-id", name: "id", type: "UUID", isPk: true },
            { id: "du-sub", name: "keycloak_sub", type: "VARCHAR(255)", isUnique: true },
            { id: "du-uname", name: "username", type: "VARCHAR(60)", isUnique: true },
            { id: "du-email", name: "email", type: "VARCHAR(255)", isUnique: true },
            { id: "du-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-dev-profiles",
        type: "tableNode",
        position: { x: 50, y: 350 },
        data: {
          label: "user_profiles",
          tableName: "user_profiles",
          subtext: "Public bio, avatar, and social links",
          badge: "TABLE",
          colorTheme: "cyan",
          columns: [
            { id: "dp-id", name: "id", type: "UUID", isPk: true },
            { id: "dp-uid", name: "user_id", type: "UUID", isFk: true, isUnique: true },
            { id: "dp-bio", name: "bio", type: "TEXT", isNullable: true },
            { id: "dp-avatar", name: "avatar_url", type: "VARCHAR(500)", isNullable: true },
            { id: "dp-xp", name: "reputation_points", type: "INTEGER" },
          ],
        },
      },
      {
        id: "tbl-dev-problems",
        type: "tableNode",
        position: { x: 440, y: 60 },
        data: {
          label: "problems",
          tableName: "problems",
          subtext: "Bug reports and programming questions",
          badge: "TABLE",
          colorTheme: "emerald",
          columns: [
            { id: "dpr-id", name: "id", type: "UUID", isPk: true },
            { id: "dpr-author", name: "author_id", type: "UUID", isFk: true },
            { id: "dpr-title", name: "title", type: "VARCHAR(300)" },
            { id: "dpr-body", name: "description", type: "TEXT" },
            { id: "dpr-views", name: "view_count", type: "BIGINT" },
            { id: "dpr-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-dev-solutions",
        type: "tableNode",
        position: { x: 440, y: 380 },
        data: {
          label: "solutions",
          tableName: "solutions",
          subtext: "Answers and code showcases",
          badge: "TABLE",
          colorTheme: "purple",
          columns: [
            { id: "ds-id", name: "id", type: "UUID", isPk: true },
            { id: "ds-prob-id", name: "problem_id", type: "UUID", isFk: true },
            { id: "ds-author", name: "author_id", type: "UUID", isFk: true },
            { id: "ds-accepted", name: "is_accepted", type: "BOOLEAN" },
            { id: "ds-upvotes", name: "upvote_count", type: "INTEGER" },
            { id: "ds-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
      {
        id: "tbl-dev-comments",
        type: "tableNode",
        position: { x: 830, y: 380 },
        data: {
          label: "comments",
          tableName: "comments",
          subtext: "Threaded discussions on solutions",
          badge: "TABLE",
          colorTheme: "amber",
          columns: [
            { id: "dc-id", name: "id", type: "UUID", isPk: true },
            { id: "dc-sol-id", name: "solution_id", type: "UUID", isFk: true },
            { id: "dc-author", name: "author_id", type: "UUID", isFk: true },
            { id: "dc-content", name: "content", type: "TEXT" },
            { id: "dc-created", name: "created_at", type: "TIMESTAMP" },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e-dev-u-prof",
        source: "tbl-dev-users",
        sourceHandle: "col-left-du-id",
        target: "tbl-dev-profiles",
        targetHandle: "col-left-dp-uid",
        label: "1 : 1 (user profile)",
        animated: false,
      },
      {
        id: "e-dev-u-prob",
        source: "tbl-dev-users",
        sourceHandle: "col-right-du-id",
        target: "tbl-dev-problems",
        targetHandle: "col-left-dpr-author",
        label: "1 : N (created problems)",
        animated: false,
      },
      {
        id: "e-dev-prob-sol",
        source: "tbl-dev-problems",
        sourceHandle: "col-right-dpr-id",
        target: "tbl-dev-solutions",
        targetHandle: "col-left-ds-prob-id",
        label: "1 : N (solutions)",
        animated: false,
      },
      {
        id: "e-dev-sol-comm",
        source: "tbl-dev-solutions",
        sourceHandle: "col-right-ds-id",
        target: "tbl-dev-comments",
        targetHandle: "col-left-dc-sol-id",
        label: "1 : N (comments)",
        animated: false,
      },
    ],
  },
  {
    id: "system-architecture",
    name: "System Architecture",
    description: "Standard web app stack: Client → API Gateway → Server → DB & Cache",
    nodes: [
      {
        id: "client-1",
        type: "clientNode",
        position: { x: 50, y: 150 },
        data: {
          label: "Next.js Web Client",
          subtext: "App Router & RTK Query",
          badge: "Frontend",
        },
      },
      {
        id: "gateway-1",
        type: "cloudNode",
        position: { x: 340, y: 150 },
        data: {
          label: "API Gateway / Proxy",
          subtext: "Auth verification & routing",
          badge: "Gateway",
        },
      },
      {
        id: "server-1",
        type: "serverNode",
        position: { x: 630, y: 150 },
        data: {
          label: "Spring Boot Core API",
          subtext: "Business logic & services",
          badge: "Backend",
        },
      },
      {
        id: "db-1",
        type: "databaseNode",
        position: { x: 920, y: 80 },
        data: {
          label: "PostgreSQL Database",
          subtext: "Primary persistent store",
          badge: "SQL DB",
        },
      },
      {
        id: "cache-1",
        type: "databaseNode",
        position: { x: 920, y: 220 },
        data: {
          label: "Redis Cache",
          subtext: "Session & query caching",
          badge: "Cache",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "client-1",
        target: "gateway-1",
        animated: true,
        label: "HTTPS / REST",
      },
      {
        id: "e2",
        source: "gateway-1",
        target: "server-1",
        animated: true,
        label: "Internal gRPC",
      },
      {
        id: "e3",
        source: "server-1",
        target: "db-1",
        label: "Read / Write",
      },
      {
        id: "e4",
        source: "server-1",
        target: "cache-1",
        label: "Cache Hit / Miss",
      },
    ],
  },
  {
    id: "auth-oauth-flow",
    name: "Auth & OAuth Flow",
    description: "PKCE OIDC sequence: User → Better Auth → Keycloak → Protected API",
    nodes: [
      {
        id: "auth-client",
        type: "clientNode",
        position: { x: 50, y: 150 },
        data: {
          label: "Client App",
          subtext: "better-auth PKCE initiate",
          badge: "Client",
        },
      },
      {
        id: "auth-idp",
        type: "cloudNode",
        position: { x: 340, y: 70 },
        data: {
          label: "Keycloak OIDC Server",
          subtext: "Issues JWT access & refresh tokens",
          badge: "IdP",
        },
      },
      {
        id: "auth-decision",
        type: "decisionNode",
        position: { x: 340, y: 230 },
        data: {
          label: "Bearer token valid?",
          badge: "Verify JWT",
        },
      },
      {
        id: "auth-api",
        type: "serverNode",
        position: { x: 630, y: 230 },
        data: {
          label: "Protected API Service",
          subtext: "Returns user data & records",
          badge: "Resource Server",
        },
      },
    ],
    edges: [
      {
        id: "ea-1",
        source: "auth-client",
        target: "auth-idp",
        animated: true,
        label: "1. Login (PKCE)",
      },
      {
        id: "ea-2",
        source: "auth-idp",
        target: "auth-client",
        label: "2. Session & Token",
      },
      {
        id: "ea-3",
        source: "auth-client",
        target: "auth-decision",
        animated: true,
        label: "3. Request with Bearer",
      },
      {
        id: "ea-4",
        source: "auth-decision",
        target: "auth-api",
        label: "Yes: Allow request",
      },
    ],
  },
  {
    id: "microservices-pipeline",
    name: "Microservices & Queue",
    description: "Event-driven workflow with Message Queue & Async Workers",
    nodes: [
      {
        id: "ms-client",
        type: "clientNode",
        position: { x: 50, y: 140 },
        data: {
          label: "Web / Mobile Client",
          subtext: "Uploads payload / dispatches job",
          badge: "Frontend",
        },
      },
      {
        id: "ms-api",
        type: "serverNode",
        position: { x: 330, y: 140 },
        data: {
          label: "Ingestion API",
          subtext: "Validates and enqueues task",
          badge: "API",
        },
      },
      {
        id: "ms-queue",
        type: "cloudNode",
        position: { x: 610, y: 140 },
        data: {
          label: "RabbitMQ / Kafka Queue",
          subtext: "Asynchronous task queue",
          badge: "Event Broker",
        },
      },
      {
        id: "ms-worker",
        type: "serverNode",
        position: { x: 890, y: 80 },
        data: {
          label: "Processing Worker",
          subtext: "Executes heavy background task",
          badge: "Worker",
        },
      },
      {
        id: "ms-db",
        type: "databaseNode",
        position: { x: 890, y: 220 },
        data: {
          label: "Storage & State",
          subtext: "Saves results & status",
          badge: "Database",
        },
      },
    ],
    edges: [
      {
        id: "em-1",
        source: "ms-client",
        target: "ms-api",
        animated: true,
        label: "POST /jobs",
      },
      {
        id: "em-2",
        source: "ms-api",
        target: "ms-queue",
        animated: true,
        label: "Publish Event",
      },
      {
        id: "em-3",
        source: "ms-queue",
        target: "ms-worker",
        animated: true,
        label: "Consume Event",
      },
      {
        id: "em-4",
        source: "ms-worker",
        target: "ms-db",
        label: "Persist Result",
      },
    ],
  },
];

