import {
  Profile,
  ProfileBadge,
  ProfileStats,
  SeverityStats,
  HacktivityEntry,
  ThanksEntry,
  EditProfileFormData,
  AccountStatus,
  FollowRecord,
  FollowingCounts,
} from "./types";

export const mockProfile: Profile = {
  id: "usr_narongseu",
  username: "narongseu",
  displayName: "Narong Seu",
  avatarInitials: "NR",
  bio: "Full-stack security researcher specializing in API abuse, server-side vulnerabilities, and OAuth misconfigurations. I enjoy finding critical bugs in authentication flows and payment systems. Open to private program invitations.",
  location: "Phnom Penh, Cambodia",
  memberSince: "March 2023",
  socialLinks: {
    website: "ghostkode.dev",
    github: "ghostkode",
    twitter: "@ghostkode_sec",
  },
  followers: 284,
  following: 61,
  isOwnProfile: true,
};

export const mockStats: ProfileStats = {
  reputation: 9310,
  globalRank: 7,
  reportsSubmitted: 148,
  accepted: 121,
  acceptedRate: 81.8,
  totalEarned: 42800,
};

export const mockSeverity: SeverityStats = {
  critical: 14,
  high: 38,
  medium: 49,
  low: 20,
  rejected: 18,
  duplicate: 9,
  retests: 22,
};

export const mockBadges: ProfileBadge[] = [
  { id: "b1", label: "Top 10 Global", icon: "trophy", locked: false },
  { id: "b2", label: "Century", icon: "shield", locked: false },
  { id: "b3", label: "First Critical", icon: "zap", locked: false },
  { id: "b4", label: "Speed Demon", icon: "activity", locked: false },
  { id: "b5", label: "Community Star", icon: "star", locked: false },
  { id: "b6", label: "Retest Ace", icon: "target", locked: false },
  { id: "b7", label: "Hall of Fame", icon: "crown", locked: true },
  { id: "b8", label: "500 Club", icon: "shield", locked: true },
  { id: "b9", label: "Critical Hunter", icon: "zap", locked: true },
];

export const mockHacktivity: HacktivityEntry[] = [
  { id: "h1", type: "resolved", actorHandle: "@ghostkode", date: "2025-07-01", severity: "critical", program: "CloudVault", bounty: 8000 },
  { id: "h2", type: "badge", actorHandle: "@ghostkode", date: "2025-06-29", badgeName: "Speed Demon" },
  { id: "h3", type: "resolved", actorHandle: "@ghostkode", date: "2025-06-22", severity: "high", program: "FinTrack API", bounty: 3500 },
  { id: "h4", type: "rank", actorHandle: "@ghostkode", date: "2025-06-18", rankLabel: "#7 Global" },
  { id: "h5", type: "retest", actorHandle: "@ghostkode", date: "2025-06-12", program: "DataBridge" },
  { id: "h6", type: "resolved", actorHandle: "@ghostkode", date: "2025-05-28", severity: "critical", program: "AuthFlow", bounty: 12000 },
  { id: "h7", type: "badge", actorHandle: "@ghostkode", date: "2025-05-20", badgeName: "Century" },
  { id: "h8", type: "resolved", actorHandle: "@ghostkode", date: "2025-05-14", severity: "high", program: "ShieldNet", bounty: 4200 },
];

export const mockThanks: ThanksEntry[] = [
  {
    id: "t1",
    orgName: "Anna Cook",
    message:
      "We truly appreciate your time reporting a critical vulnerability in our system. Your responsible disclosure has helped us protect thousands of users.",
    date: "2026-06-08",
  },
  {
    id: "t2",
    orgName: "Anna Cook",
    message:
      "We truly appreciate your time reporting a critical vulnerability in our system. Your responsible disclosure has helped us protect thousands of users.",
    date: "2026-06-08",
  },
  {
    id: "t3",
    orgName: "Anna Cook",
    message:
      "We truly appreciate your time reporting a critical vulnerability in our system. Your responsible disclosure has helped us protect thousands of users.",
    date: "2026-06-08",
  },
];

export const mockEditProfileFormData: EditProfileFormData = {
  avatarInitials: "NR",
  fullName: "Narong Seu",
  username: "narongseu",
  email: "narong.seu@example.com",
  accountType: "User",
  bio: mockProfile.bio,
  location: "Phnom Penh, Cambodia",
  socialLinks: {
    github: "ghostkode",
    twitter: "@ghostkode_sec",
    linkedin: "",
    website: "ghostkode.dev",
  },
  twoFactorEnabled: false,
  notifications: {
    reportStatusChanges: { inApp: true, email: true },
    adminApprovals: { inApp: true, email: false },
    newPrograms: { inApp: true, email: false },
    retestInvites: { inApp: true, email: true },
    communityActivity: { inApp: false, email: false },
    followActivity: { inApp: false, email: false },
  },
};

export const mockAccountStatus: AccountStatus = {
  memberSince: "Mar 2023",
  totalSubmissions: mockStats.reportsSubmitted,
  acceptedReports: mockStats.accepted,
  reputationPoints: mockStats.reputation,
  acceptanceRate: mockStats.acceptedRate,
};
export const mockEditProfileForm: EditProfileFormData = {
  avatarInitials: "AK",
  avatarUrl: undefined,
  fullName: "Alex Kim",
  username: "alexkim",
  email: "alex.kim@example.com",
  accountType: "Hacker",
  bio: "Security researcher focused on web app vulnerabilities and API security. Love breaking things to make them safer.",
  location: "San Francisco, CA",
  phone: "",
  dateOfBirth: "",
  gender: undefined,
  socialLinks: {
    github: "https://github.com/alexkim",
    twitter: "https://twitter.com/alexkim",
    linkedin: "https://linkedin.com/in/alexkim",
    website: "https://alexkim.dev",
  },
  twoFactorEnabled: true,
  notifications: {
    reportStatusChanges: { inApp: true, email: true },
    adminApprovals: { inApp: true, email: false },
    newPrograms: { inApp: false, email: false },
    retestInvites: { inApp: true, email: true },
    communityActivity: { inApp: false, email: false },
    followActivity: { inApp: true, email: false },
  },
};

export const mockFollowersList: FollowRecord[] = [
  {
    id: "flw_sophanith",
    followableType: "USER",
    followableId: "usr_sophanith",
    createdAt: "2026-05-12T10:30:00Z",
    displayName: "Sophanith Kim",
    username: "sophanith_kim",
    avatarInitials: "SK",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    bio: "Senior Security Engineer at CyberGate. Specializes in cloud infrastructure and Kubernetes security.",
    reputation: 1420,
    isFollowing: true,
  },
  {
    id: "flw_vireak",
    followableType: "USER",
    followableId: "usr_vireak",
    createdAt: "2026-04-18T14:15:00Z",
    displayName: "Vireak Chea",
    username: "vireak_sec",
    avatarInitials: "VC",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
    bio: "Web3 & Smart Contract Auditor. Found 30+ critical bugs in DeFi protocols.",
    reputation: 2890,
    isFollowing: false,
  },
  {
    id: "flw_chantra",
    followableType: "USER",
    followableId: "usr_chantra",
    createdAt: "2026-03-22T09:40:00Z",
    displayName: "Chantra Soun",
    username: "chantra_s",
    avatarInitials: "CS",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80",
    bio: "Bug Bounty Hunter & OAuth Expert. Passionate about API abuse and zero-trust security.",
    reputation: 890,
    isFollowing: true,
  },
  {
    id: "flw_elena",
    followableType: "USER",
    followableId: "usr_elena",
    createdAt: "2026-02-14T16:50:00Z",
    displayName: "Elena Rostova",
    username: "elena_sec",
    avatarInitials: "ER",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80",
    bio: "DevSolve Top 5 Researcher. Focuses on browser security and WASM sandbox escapes.",
    reputation: 4120,
    isFollowing: true,
  },
  {
    id: "flw_sokha",
    followableType: "USER",
    followableId: "usr_sokha",
    createdAt: "2026-01-08T11:20:00Z",
    displayName: "Sokha Heng",
    username: "sokha_dev",
    avatarInitials: "SH",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
    bio: "Full-stack Developer & Pentester. Building open-source security tools in Rust.",
    reputation: 650,
    isFollowing: false,
  },
];

export const mockFollowingList: FollowRecord[] = [
  {
    id: "flw_alex",
    followableType: "USER",
    followableId: "usr_alex",
    createdAt: "2026-04-10T12:00:00Z",
    displayName: "Alex Rivers",
    username: "alex_rivers",
    avatarInitials: "AR",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=250&q=80",
    bio: "Zero-day Researcher & Linux Kernel Exploit Developer.",
    reputation: 5600,
    isFollowing: true,
  },
  {
    id: "flw_sarah",
    followableType: "USER",
    followableId: "usr_sarah",
    createdAt: "2026-03-15T08:30:00Z",
    displayName: "Sarah Connor",
    username: "sarah_c",
    avatarInitials: "SC",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80",
    bio: "Cloud Security Architect & AWS Community Builder.",
    reputation: 3210,
    isFollowing: true,
  },
  {
    id: "flw_cloudvault",
    followableType: "ORGANIZATION",
    followableId: "org_cloudvault",
    createdAt: "2026-02-20T15:10:00Z",
    displayName: "CloudVault Security",
    username: "cloudvault",
    avatarInitials: "CV",
    avatarUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=250&q=80",
    bio: "Enterprise Data Protection & Zero-Trust Encryption Platform.",
    reputation: 12500,
    isFollowing: true,
  },
  {
    id: "flw_fintrack",
    followableType: "ORGANIZATION",
    followableId: "org_fintrack",
    createdAt: "2026-01-25T11:45:00Z",
    displayName: "FinTrack Systems",
    username: "fintrack",
    avatarInitials: "FT",
    avatarUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=250&q=80",
    bio: "Fintech Infrastructure & Payment Security Vulnerability Disclosure Program.",
    reputation: 9800,
    isFollowing: true,
  },
  {
    id: "flw_topic_api",
    followableType: "TOPIC",
    followableId: "topic_api_security",
    createdAt: "2025-12-10T09:00:00Z",
    displayName: "API Security & OAuth 2.1",
    username: "api-security",
    bio: "Discussions, writeups, and vulnerability reports on REST, GraphQL, and OAuth 2.1 flows.",
    reputation: 4300,
    isFollowing: true,
  },
  {
    id: "flw_topic_wasm",
    followableType: "TOPIC",
    followableId: "topic_webassembly",
    createdAt: "2025-11-05T14:20:00Z",
    displayName: "WebAssembly Security",
    username: "webassembly",
    bio: "Memory safety, sandbox escapes, and runtime isolation techniques in WebAssembly.",
    reputation: 2150,
    isFollowing: true,
  },
];

export const mockFollowingCounts: FollowingCounts = {
  hackers: 2,
  orgs: 2,
  topics: 2,
};