import { Researcher, LeaderboardStats } from './types';

export const mockResearchers: Researcher[] = [
  {
    id: '1',
    rank: 1,
    name: 'Amara Daflo',
    handle: 'dark4tch',
    reputation: 13305,
    reputationDisplay: '13,305 pts',
    accepted: 62,
    critical: 13,
    badges: ['Top 10', 'Speed Hacker', 'Bug Slayer'],
    country: 'Nigeria',
    avatar: 'https://ui-avatars.com/api/?name=Amara+Daflo&background=6366f1&color=fff',
    joinedDate: '2023-01-15',
    email: 'amara@example.com',
    bio: 'Security researcher specializing in web application vulnerabilities',
    socialLinks: {
      github: 'https://github.com/dark4tch',
      twitter: 'https://twitter.com/dark4tch',
    },
  },
  {
    id: '2',
    rank: 2,
    name: 'Ky Reaksa',
    handle: 'ky_reaksa',
    reputation: 10555,
    reputationDisplay: '10,555 pts',
    accepted: 58,
    critical: 10,
    badges: ['Bug Slayer', 'Speed Hacker'],
    country: 'Cambodia',
    avatar: 'https://ui-avatars.com/api/?name=Ky+Reaksa&background=10b981&color=fff',
    joinedDate: '2023-02-20',
    email: 'ky@example.com',
    bio: 'Bug bounty hunter and cybersecurity researcher',
    socialLinks: {
      github: 'https://github.com/kyreaksa',
      twitter: 'https://twitter.com/kyreaksa',
    },
  },
  {
    id: '3',
    rank: 3,
    name: 'Fatima Al-Rashid',
    handle: 'fatima_ar',
    reputation: 9870,
    reputationDisplay: '9,870 pts',
    accepted: 53,
    critical: 9,
    badges: ['First Blood', 'Retest Pro'],
    country: 'UAE',
    avatar: 'https://ui-avatars.com/api/?name=Fatima+Al-Rashid&background=8b5cf6&color=fff',
    joinedDate: '2023-03-10',
    email: 'fatima@example.com',
    bio: 'Penetration tester and security researcher',
    socialLinks: {
      twitter: 'https://twitter.com/fatima_ar',
      linkedin: 'https://linkedin.com/in/fatima-alrashid',
    },
  },
  {
    id: '4',
    rank: 4,
    name: 'Dim Phathea',
    handle: 'dim_p',
    reputation: 8920,
    reputationDisplay: '8,920 pts',
    accepted: 49,
    critical: 8,
    badges: ['Bug Slayer'],
    country: 'Cambodia',
    avatar: 'https://ui-avatars.com/api/?name=Dim+Phathea&background=ef4444&color=fff',
    joinedDate: '2023-04-05',
    email: 'dim@example.com',
    bio: 'Web security researcher and CTF player',
    socialLinks: {
      github: 'https://github.com/dimphathea',
    },
  },
  {
    id: '5',
    rank: 5,
    name: 'Carlos Mendez',
    handle: 'carlos_m',
    reputation: 7740,
    reputationDisplay: '7,740 pts',
    accepted: 44,
    critical: 7,
    badges: ['Speed Hacker'],
    country: 'Mexico',
    avatar: 'https://ui-avatars.com/api/?name=Carlos+Mendez&background=f59e0b&color=fff',
    joinedDate: '2023-05-12',
    email: 'carlos@example.com',
    bio: 'DevOps security and cloud security researcher',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/carlosmendez',
    },
  },
  {
    id: '6',
    rank: 6,
    name: 'Nia Otsei',
    handle: 'nia_otsei',
    reputation: 6890,
    reputationDisplay: '6,890 pts',
    accepted: 40,
    critical: 6,
    badges: ['Retest Pro'],
    country: 'Ghana',
    avatar: 'https://ui-avatars.com/api/?name=Nia+Otsei&background=ec4899&color=fff',
    joinedDate: '2023-06-18',
    email: 'nia@example.com',
    bio: 'Mobile security researcher and bug hunter',
    socialLinks: {
      twitter: 'https://twitter.com/niaotsei',
    },
  },
  {
    id: '7',
    rank: 7,
    name: 'Pavel Novikov',
    handle: 'pavel_n',
    reputation: 6120,
    reputationDisplay: '6,120 pts',
    accepted: 37,
    critical: 5,
    badges: ['First Blood'],
    country: 'Russia',
    avatar: 'https://ui-avatars.com/api/?name=Pavel+Novikov&background=14b8a6&color=fff',
    joinedDate: '2023-07-22',
    email: 'pavel@example.com',
    bio: 'Network security and penetration testing expert',
    socialLinks: {
      github: 'https://github.com/paveln',
    },
  },
  {
    id: '8',
    rank: 8,
    name: 'See Yeon Park',
    handle: 'see_park',
    reputation: 5480,
    reputationDisplay: '5,480 pts',
    accepted: 33,
    critical: 4,
    badges: ['Speed Hacker'],
    country: 'South Korea',
    avatar: 'https://ui-avatars.com/api/?name=See+Yeon+Park&background=6366f1&color=fff',
    joinedDate: '2023-08-30',
    email: 'seepark@example.com',
    bio: 'AI/ML security researcher',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/seepark',
    },
  },
  {
    id: '9',
    rank: 9,
    name: 'Riya Sharma',
    handle: 'riya_s',
    reputation: 4870,
    reputationDisplay: '4,870 pts',
    accepted: 28,
    critical: 3,
    badges: [],
    country: 'India',
    avatar: 'https://ui-avatars.com/api/?name=Riya+Sharma&background=8b5cf6&color=fff',
    joinedDate: '2023-09-14',
    email: 'riya@example.com',
    bio: 'Blockchain security researcher',
    socialLinks: {
      twitter: 'https://twitter.com/riyasharma',
    },
  },
  {
    id: '10',
    rank: 10,
    name: 'Tobias Müller',
    handle: 'tobias_m',
    reputation: 4210,
    reputationDisplay: '4,210 pts',
    accepted: 24,
    critical: 2,
    badges: [],
    country: 'Germany',
    avatar: 'https://ui-avatars.com/api/?name=Tobias+Muller&background=10b981&color=fff',
    joinedDate: '2023-10-01',
    email: 'tobias@example.com',
    bio: 'Open source security enthusiast',
    socialLinks: {
      github: 'https://github.com/tobiasm',
    },
  },
  {
    id: '11',
    rank: 11,
    name: 'Yasmine Cherkaoui',
    handle: 'yasmine_c',
    reputation: 3590,
    reputationDisplay: '3,590 pts',
    accepted: 20,
    critical: 1,
    badges: [],
    country: 'Morocco',
    avatar: 'https://ui-avatars.com/api/?name=Yasmine+Cherkaoui&background=ef4444&color=fff',
    joinedDate: '2023-11-05',
    email: 'yasmine@example.com',
    bio: 'IoT and embedded systems security',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/yasminecherkaoui',
    },
  },
  {
    id: '12',
    rank: 12,
    name: 'Arjun Kapoor',
    handle: 'arjun_k',
    reputation: 2980,
    reputationDisplay: '2,980 pts',
    accepted: 16,
    critical: 1,
    badges: [],
    country: 'India',
    avatar: 'https://ui-avatars.com/api/?name=Arjun+Kapoor&background=f59e0b&color=fff',
    joinedDate: '2023-12-10',
    email: 'arjun@example.com',
    bio: 'Junior security researcher and CTF player',
    socialLinks: {
      github: 'https://github.com/arjunk',
    },
  },
  {
    id: '13',
    rank: 13,
    name: 'Sofia Anderson',
    handle: 'sofia_a',
    reputation: 2340,
    reputationDisplay: '2,340 pts',
    accepted: 12,
    critical: 0,
    badges: [],
    country: 'Sweden',
    avatar: 'https://ui-avatars.com/api/?name=Sofia+Anderson&background=ec4899&color=fff',
    joinedDate: '2024-01-15',
    email: 'sofia@example.com',
    bio: 'Student researcher passionate about cybersecurity',
    socialLinks: {
      twitter: 'https://twitter.com/sofiaanderson',
    },
  },
  {
    id: '14',
    rank: 14,
    name: 'Tariq Hassan',
    handle: 'tariq_h',
    reputation: 1890,
    reputationDisplay: '1,890 pts',
    accepted: 8,
    critical: 0,
    badges: [],
    country: 'Egypt',
    avatar: 'https://ui-avatars.com/api/?name=Tariq+Hassan&background=14b8a6&color=fff',
    joinedDate: '2024-02-20',
    email: 'tariq@example.com',
    bio: 'Cybersecurity enthusiast and bug hunter',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/tariqhassan',
    },
  },
  {
    id: '15',
    rank: 15,
    name: 'Mei Lin Chen',
    handle: 'mei_c',
    reputation: 1450,
    reputationDisplay: '1,450 pts',
    accepted: 5,
    critical: 0,
    badges: [],
    country: 'Taiwan',
    avatar: 'https://ui-avatars.com/api/?name=Mei+Lin+Chen&background=8b5cf6&color=fff',
    joinedDate: '2024-03-25',
    email: 'mei@example.com',
    bio: 'API security researcher',
    socialLinks: {
      github: 'https://github.com/meilinc',
    },
  },
];

export const mockLeaderboardStats: LeaderboardStats = {
  totalResearchers: 2841,
  totalReports: 19430,
  totalPrograms: 312,
  topResearcher: 'Amara Daflo',
  averageReputation: 4850,
  totalBadges: 256,
  activeToday: 847,
};

export const mockBadges = [
  'Top 10',
  'Speed Hacker',
  'Bug Slayer',
  'First Blood',
  'Retest Pro',
  'Critical Hunter',
  'Report Master',
  'Quick Finder',
];

export const mockCountries = [
  'Nigeria',
  'Cambodia',
  'UAE',
  'Mexico',
  'Ghana',
  'Russia',
  'South Korea',
  'India',
  'Germany',
  'Morocco',
  'Sweden',
  'Egypt',
  'Taiwan',
];