import { LeaderboardStats, Researcher } from "./types";

export const mockLeaderboardStats: LeaderboardStats = {
  activeResearchers: 2841,
  validReports: 19430,
  programsLive: 312,
};

// Ranks 1-5 — the highlighted "top researcher" cards above the table
export const mockTopResearchers: Researcher[] = [
  {
    id: "r1",
    rank: 1,
    handle: "darkp4tch",
    realName: "Amara Diallo",
    countryCode: "sn",
    avatarInitials: "AD",
    avatarUrl: "https://i.pinimg.com/736x/28/58/cf/2858cf0eedebed2c21e7d286d62e6ee9.jpg",
    reputation: 13305,
    accepted: 91,
    critical: 14,
    badges: ["Top 10", "Bug Slayer"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "r2",
    rank: 2,
    handle: "n1ghtw0lf",
    realName: "Ivan Petrov",
    countryCode: "ru",
    avatarInitials: "IP",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 12680,
    accepted: 87,
    critical: 12,
    badges: ["Top 10", "Speed Hacker"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "r3",
    rank: 3,
    handle: "cipherqueen",
    realName: "Lin Xiaoyu",
    countryCode: "cn",
    avatarInitials: "LX",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 11920,
    accepted: 80,
    critical: 11,
    badges: ["Top 10", "First Blood"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "r4",
    rank: 4,
    handle: "byte_reaper",
    realName: "Diego Alvarez",
    countryCode: "mx",
    avatarInitials: "DA",
      avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 11305,
    accepted: 76,
    critical: 9,
    badges: ["Top 10", "Retest Pro"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "r5",
    rank: 5,
    handle: "ghostsh3ll",
    realName: "Fatima Noor",
    countryCode: "pk",
    avatarInitials: "FN",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 10890,

    accepted: 71,
    critical: 8,
    badges: ["Top 10", "Bug Slayer"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
];

// Ranks 4-15 — the table rows (rank 4 & 5 intentionally overlap with the
// highlighted cards above, matching the reference design)
export const mockRankingTable: Researcher[] = [
  {
    id: "t4",
    rank: 4,
    handle: "Ky Reaksa",
    realName: "Fatima Al-Rashid",
    countryCode: "sa",
    avatarInitials: "KR",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 10555,
    accepted: 62,
    critical: 7,
    badges: ["Bug Slayer", "Speed Hacker"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t5",
    rank: 5,
    handle: "Dim Phathea",
    realName: "Carlos Mendez",
    countryCode: "mx",
    avatarInitials: "DP",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 9870,
    accepted: 58,
    critical: 6,
    badges: ["First Blood", "Retest Pro"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t6",
    rank: 6,
    handle: "San Tol",
    realName: "Nia Osei",
    countryCode: "gh",
    avatarInitials: "ST",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 8920,
    accepted: 53,
    critical: 5,
    badges: ["Bug Slayer"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t7",
    rank: 7,
    handle: "h4ck_atlas",
    realName: "Pavel Novikov",
    countryCode: "ru",
    avatarInitials: "PN",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 7740,
    accepted: 49,
    critical: 4,
    badges: ["Speed Hacker"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t8",
    rank: 8,
    handle: "bts Jungkook",
    realName: "Seo Yeon Park",
    countryCode: "kr",
    avatarInitials: "SP",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 6890,
    accepted: 44,
    critical: 3,
    badges: ["Retest Pro"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t9",
    rank: 9,
    handle: "v3ct0r_x",
    realName: "Riya Sharma",
    countryCode: "in",
    avatarInitials: "RS",
    avatarUrl: "https://i.pinimg.com/736x/f7/1f/54/f71f54635e921407059cd31926b74229.jpg",
    reputation: 6120,
    accepted: 40,
    critical: 2,
    badges: ["First Blood"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t10",
    rank: 10,
    handle: "shellsh0ck",
    realName: "Tobias Müller",
    countryCode: "de",
    avatarInitials: "TM",
    reputation: 5480,
    accepted: 37,
    critical: 2,
    badges: ["Speed Hacker"],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t11",
    rank: 11,
    handle: "pixelp0wn",
    realName: "Yasmine Cherkaoui",
    countryCode: "ma",
    avatarInitials: "YC",
    reputation: 4870,
    accepted: 33,
    critical: 1,
    badges: [],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t12",
    rank: 12,
    handle: "deadc0de",
    realName: "Arjun Kapoor",
    countryCode: "in",
    avatarInitials: "AK",
    reputation: 4210,
    accepted: 28,
    critical: 1,
    badges: [],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t13",
    rank: 13,
    handle: "bl4ckm1rror",
    realName: "Sofia Andersson",
    countryCode: "se",
    avatarInitials: "SA",
    reputation: 3590,
    accepted: 24,
    critical: 0,
    badges: [],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t14",
    rank: 14,
    handle: "zeroway",
    realName: "Tariq Hassan",
    countryCode: "eg",
    avatarInitials: "TH",
    reputation: 2980,
    accepted: 20,
    critical: 0,
    badges: [],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
  {
    id: "t15",
    rank: 15,
    handle: "exploit_echo",
    realName: "Mei Lin Chen",
    countryCode: "tw",
    avatarInitials: "ML",
    reputation: 2340,
    accepted: 16,
    critical: 0,
    badges: [],
    level: 3,
    trend: { direction: "up", value: Math.floor(Math.random() * 10) + 1 },
    categories: ["Best Talk", "Best Interactivity", "Talk to Listen Ratio"],
    achievements: [
      { id: "a1", level: 1, label: "Talk to Listen Ratio", value: 5, color: "blue" },
      { id: "a2", level: 3, label: "Positive Sentiment", value: 30, color: "blue" },
      { id: "a3", level: 4, label: "Number of Questions", value: 60, color: "cyan" },
      { id: "a4", level: 2, label: "Conversations", value: 15, color: "purple" }
    ],
    levelProgress: 87,
  },
];
